# Buttons and system clock
set_property PACKAGE_PIN N17 [get_ports TOUCH]
set_property IOSTANDARD LVCMOS33 [get_ports TOUCH]
set_property PACKAGE_PIN M18 [get_ports START]
set_property IOSTANDARD LVCMOS33 [get_ports START]
set_property PACKAGE_PIN M17 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN E3 [get_ports CLK]
	
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets RESET_IBUF]

# Crash LED
set_property IOSTANDARD LVCMOS33 [get_ports crash]
set_property PACKAGE_PIN H17 [get_ports crash]

# Anode output and CONTROL_TOP
set_property PACKAGE_PIN J17 [get_ports AN_TOP[0]]
set_property PACKAGE_PIN J18 [get_ports AN_TOP[1]]
set_property PACKAGE_PIN T9 [get_ports AN_TOP[2]]
set_property PACKAGE_PIN J14 [get_ports AN_TOP[3]]
set_property PACKAGE_PIN P14 [get_ports AN_TOP[4]]
set_property PACKAGE_PIN T14 [get_ports AN_TOP[5]]
set_property PACKAGE_PIN K2 [get_ports AN_TOP[6]]
set_property PACKAGE_PIN U13 [get_ports AN_TOP[7]]
set_property IOSTANDARD LVCMOS33 [get_ports AN_TOP[0]]
set_property IOSTANDARD LVCMOS33 [get_ports AN_TOP[1]]
set_property IOSTANDARD LVCMOS33 [get_ports AN_TOP[2]]
set_property IOSTANDARD LVCMOS33 [get_ports AN_TOP[3]]
set_property IOSTANDARD LVCMOS33 [get_ports AN_TOP[4]]
set_property IOSTANDARD LVCMOS33 [get_ports AN_TOP[5]]
set_property IOSTANDARD LVCMOS33 [get_ports AN_TOP[6]]
set_property IOSTANDARD LVCMOS33 [get_ports AN_TOP[7]]
set_property PACKAGE_PIN T10 [get_ports CONTROL_TOP[6]]
set_property PACKAGE_PIN R10 [get_ports CONTROL_TOP[5]]
set_property PACKAGE_PIN K16 [get_ports CONTROL_TOP[4]]
set_property PACKAGE_PIN K13 [get_ports CONTROL_TOP[3]]
set_property PACKAGE_PIN P15 [get_ports CONTROL_TOP[2]]
set_property PACKAGE_PIN T11 [get_ports CONTROL_TOP[1]]
set_property PACKAGE_PIN L18 [get_ports CONTROL_TOP[0]]
set_property IOSTANDARD LVCMOS33 [get_ports CONTROL_TOP[0]]
set_property IOSTANDARD LVCMOS33 [get_ports CONTROL_TOP[1]]
set_property IOSTANDARD LVCMOS33 [get_ports CONTROL_TOP[2]]
set_property IOSTANDARD LVCMOS33 [get_ports CONTROL_TOP[3]]
set_property IOSTANDARD LVCMOS33 [get_ports CONTROL_TOP[4]]
set_property IOSTANDARD LVCMOS33 [get_ports CONTROL_TOP[5]]
set_property IOSTANDARD LVCMOS33 [get_ports CONTROL_TOP[6]]

# VGA CONTROL_TOP
set_property PACKAGE_PIN B11 [get_ports vga_hs]
set_property PACKAGE_PIN B12 [get_ports vga_vs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vs]

# VGA output - Red
set_property PACKAGE_PIN A4 [get_ports vga_r[3]]
set_property PACKAGE_PIN C5 [get_ports vga_r[2]]
set_property PACKAGE_PIN B4 [get_ports vga_r[1]]
set_property PACKAGE_PIN A3 [get_ports vga_r[0]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_r[3]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_r[2]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_r[1]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_r[0]]

# VGA output - Green
set_property PACKAGE_PIN A6 [get_ports vga_g[3]]
set_property PACKAGE_PIN B6 [get_ports vga_g[2]]
set_property PACKAGE_PIN A5 [get_ports vga_g[1]]
set_property PACKAGE_PIN C6 [get_ports vga_g[0]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_g[3]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_g[2]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_g[1]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_g[0]]

# VGA output - Blue
set_property PACKAGE_PIN D8 [get_ports vga_b[3]]
set_property PACKAGE_PIN D7 [get_ports vga_b[2]]
set_property PACKAGE_PIN C7 [get_ports vga_b[1]]
set_property PACKAGE_PIN B7 [get_ports vga_b[0]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_b[3]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_b[2]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_b[1]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_b[0]]

