# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/OneDrive/VivadoProj/EE332/flappy_bird/flappy_bird.srcs/sources_1/ip/clk_wiz_100m_40m/clk_wiz_100m_40m.xci
# IP: The module: 'clk_wiz_100m_40m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/VivadoProj/EE332/flappy_bird/flappy_bird.srcs/sources_1/ip/clk_wiz_100m_40m/clk_wiz_100m_40m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100m_40m'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/OneDrive/VivadoProj/EE332/flappy_bird/flappy_bird.srcs/sources_1/ip/clk_wiz_100m_40m/clk_wiz_100m_40m.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100m_40m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/OneDrive/VivadoProj/EE332/flappy_bird/flappy_bird.srcs/sources_1/ip/clk_wiz_100m_40m/clk_wiz_100m_40m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100m_40m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/OneDrive/VivadoProj/EE332/flappy_bird/flappy_bird.srcs/sources_1/ip/clk_wiz_100m_40m/clk_wiz_100m_40m.xci
# IP: The module: 'clk_wiz_100m_40m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/VivadoProj/EE332/flappy_bird/flappy_bird.srcs/sources_1/ip/clk_wiz_100m_40m/clk_wiz_100m_40m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100m_40m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/OneDrive/VivadoProj/EE332/flappy_bird/flappy_bird.srcs/sources_1/ip/clk_wiz_100m_40m/clk_wiz_100m_40m.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100m_40m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/OneDrive/VivadoProj/EE332/flappy_bird/flappy_bird.srcs/sources_1/ip/clk_wiz_100m_40m/clk_wiz_100m_40m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100m_40m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
